### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by vbootstrap** [taniman/gunbotproxycommunity#7]
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:422)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:683)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vbootstrap** [comment]
This was on 0.9.1

**Comment by taniman** [comment]
If the bot kept running after this, than no problem.  But I miss  the good part of that error message.  Or was that the complete message? If that was all, than some other instance did an invalid request to your server. And we could not handle it. It does not affect the proxy.

**Comment by vbootstrap** [comment]
Yeah that was the entire error

**Comment by taniman** [comment]
Will close for now. If it really affects the bot, we will take a look.

**Comment by hbellizzi** [comment]
same error.

**Comment by beemster** [comment]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

1.8.0_151
Jan 18, 2018 9:01:26 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jan 18, 2018 9:01:26 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.15
Jan 18, 2018 9:01:27 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
2018-01-18 21:01:32 INFO Util - Detected configuration changes
Jan 18, 2018 9:01:32 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8081"]
Jan 18, 2018 9:01:32 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8081"]
Jan 18, 2018 9:01:32 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
2018-01-18 21:01:32 INFO ProfitTrailerService - Normal Heartbeat
2018-01-18 21:01:32 INFO ProfitTrailerService - DCA Heartbeat
2018-01-18 21:01:34 INFO ProfitTrailerService - Cache Heartbeat
Jan 18, 2018 9:02:10 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:422)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:683)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2018-01-18 21:02:22 INFO AverageCalculator - Please set BCCBTC_bought_price
2018-01-18 21:03:15 INFO AverageCalculator - Please set DASHBTC_bought_price

**Comment by moguli** [comment]
I meet the same exception at same time in different VPS. But I don't know it's PT's problem or Binance's problem.
